name: Test CodableDatastore

on:
  pull_request:
    branches:
    - main

jobs:
  Test-Release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Swift Version
      run: |
        swift --version
    - name: Build
      run: |
        swift build --build-tests --configuration release -Xswiftc -enable-testing -Xswiftc -warnings-as-errors
    - name: Run Tests
      run: |
        swift test --skip-build --configuration release

  Test-Debug:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Swift Version
      run: |
        swift --version
    - name: Build
      run: |
        swift build --build-tests --configuration debug -Xswiftc -enable-testing -Xswiftc -warnings-as-errors
    - name: Run Tests
      run: |
        swift test --skip-build --configuration debug
